server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/msa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: passowrd
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      format-sql: true
      hibernate:
        show-sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0