spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/msa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: passowrd
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      format-sql: true
      hibernate:
        show-sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 19092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0